company_dict = {
    "20MICRONS": "20 Microns Limited",
    "21STCENMGM": "21st Century Management Services Limited",
    "3IINFOTECH": "3i Infotech Limited",
    "3MINDIA": "3M India Limited",
    "3PLAND": "3P Land Holdings Limited",
    "5PAISA": "5Paisa CapitalLimited",
    "63MOONS": "63 moons technologies limited",
    "A2ZINFRA": "A2Z Infra Engineering Limited",
    "AARTIDRUGS": "Aarti Drugs Limited",
    "AARTIIND": "Aarti IndustriesLimited",
    "AARVEEDEN": "Aarvee Denims & Exports Limited",
    "AAVAS": "Aavas Financiers Limited",
    "ABAN": "Aban Offshore Limited",
    "ABB": "ABB India Limited",
    "ABBOTINDIA": "Abbott India Limited",
    "ABCAPITAL": "Aditya Birla Capital Limited",
    "ABFRL": "Aditya Birla Fashionand Retail Limited",
    "ABMINTLTD": "ABM International Limited",
    "ACC": "ACC Limited",
    "ACCELYA": "Accelya Solutions India Limited",
    "ACE": "Action Construction Equipment Limited",
    "ADANIENT": "Adani Enterprises Limited",
    "ADANIGAS": "Adani Gas Limited",
    "ADANIGREEN": "Adani Green EnergyLimited",
    "ADANIPORTS": "Adani Ports and Special Economic Zone Limited",
    "ADANIPOWER": "Adani Power Limited",
    "ADANITRANS": "Adani TransmissionLimited",
    "ADFFOODS": "ADF Foods Limited",
    "ADHUNIK": "Adhunik Metaliks Limited",
    "ADHUNIKIND": "Adhunik Industries Limited",
    "ADLABS": "Adlabs Entertainment Limited",
    "ADORWELD": "Ador Welding Limited",
    "ADROITINFO": "Adroit Infotech Limited",
    "ADSL": "Allied Digital Services Limited",
    "ADVANIHOTR": "Advani Hotels & Resorts (India) Limited",
    "ADVENZYMES": "Advanced Enzyme Technologies Limited",
    "AEGISCHEM": "AegisLogisticsLimited",
    "AFFLE": "Affle (India) Limited",
    "AGARIND": "Agarwal Industrial Corporation Limited",
    "AGCNET": "AGC Networks Limited",
    "AGRITECH": "Agri-Tech (India) Limited",
    "AGROPHOS": "AgroPhos India Limited",
    "AHLEAST": "Asian Hotels (East) Limited",
    "AHLUCONT": "Ahluwalia Contracts (India) Limited",
    "AHLWEST": "Asian Hotels (West) Limited",
    "AIAENG": "AIA Engineering Limited",
    "AIONJSW": "Monnet Ispat & Energy Limited",
    "AIRAN": "Airan Limited",
    "AJANTPHARM": "Ajanta Pharma Limited",
    "AJMERA": "Ajmera Realty & Infra India Limited",
    "AKASH": "Akash Infra-Projects Limited",
    "AKSHARCHEM": "AksharChem India Limited",
    "AKSHOPTFBR": "Aksh Optifibre Limited",
    "AKZOINDIA": "Akzo Nobel India Limited",
    "ALANKIT": "Alankit Limited",
    "ALBERTDAVD": "Albert David Limited",
    "ALBK": "Allahabad Bank",
    "ALCHEM": "Alchemist Limited",
    "ALEMBICLTD": "Alembic Limited",
    "ALICON": "Alicon Castalloy Limited",
    "ALKALI": "Alkali Metals Limited",
    "ALKEM": "Alkem Laboratories Limited",
    "ALKYLAMINE": "Alkyl Amines Chemicals Limited",
    "ALLCARGO": "Allcargo Logistics Limited",
    "ALLSEC": "Allsec Technologies Limited",
    "ALMONDZ": "Almondz Global Securities Limited",
    "ALOKTEXT": "Alok IndustriesLimited",
    "ALPA": "Alpa Laboratories Limited",
    "ALPHAGEO": "Alphageo (India) Limited",
    "ALPSINDUS": "Alps Industries Limited",
    "AMARAJABAT": "Amara Raja BatteriesLimited",
    "AMBER": "Amber Enterprises India Limited",
    "AMBIKCO": "Ambika Cotton Mills Limited",
    "AMBUJACEM": "Ambuja Cements Limited",
    "AMDIND": "AMD Industries Limited",
    "AMJLAND": "Amj Land Holdings Limited",
    "AMRUTANJAN": "Amrutanjan Health Care Limited",
    "ANANTRAJ": "Anant Raj Limited",
    "ANDHRABANK": "Andhra Bank",
    "ANDHRACEMT": "Andhra Cements Limited",
    "ANDHRSUGAR": "The Andhra Sugars Limited",
    "ANIKINDS": "Anik Industries Limited",
    "ANKITMETAL": "Ankit Metal & Power Limited",
    "ANSALAPI": "Ansal Properties & Infrastructure Limited",
    "ANSALHSG": "Ansal Housing Limited",
    "ANTGRAPHIC": "Antarctica Limited",
    "ANUP": "The Anup Engineering Limited",
    "APARINDS": "Apar Industries Limited",
    "APCL": "Anjani Portland Cement Limited",
    "APCOTEXIND": "Apcotex Industries Limited",
    "APEX": "Apex Frozen Foods Limited",
    "APLAPOLLO": "APL Apollo Tubes Limited",
    "APLLTD": "Alembic Pharmaceuticals Limited",
    "APOLLO": "Apollo Micro Systems Limited",
    "APOLLOHOSP": "Apollo Hospitals Enterprise Limited",
    "APOLLOPIPE": "Apollo Pipes Limited",
    "APOLLOTYRE": "Apollo TyresLimited",
    "APOLSINHOT": "Apollo Sindoori Hotels Limited",
    "APTECHT": "Aptech Limited",
    "ARCHIDPLY": "Archidply Industries Limited",
    "ARCHIES": "Archies Limited",
    "ARCOTECH": "Arcotech Limited",
    "ARENTERP": "Rajdarshan Industries Limited",
    "ARIES": "Aries Agro Limited",
    "ARIHANT": "Arihant Foundations & Housing Limited",
    "ARIHANTSUP": "Arihant Superstructures Limited",
    "ARMANFIN": "Arman Financial Services Limited",
    "AROGRANITE": "Aro Granite Industries Limited",
    "ARROWGREEN": "Arrow Greentech Limited",
    "ARROWTEX": "Arrow Textiles Limited",
    "ARSHIYA": "Arshiya Limited",
    "ARSSINFRA": "ARSS Infrastructure Projects Limited",
    "ARVIND": "Arvind Limited",
    "ARVINDFASN": "Arvind FashionsLimited",
    "ARVSMART": "Arvind SmartSpaces Limited",
    "ASAHIINDIA": "Asahi IndiaGlassLimited",
    "ASAHISONG": "Asahi Songwon Colors Limited",
    "ASAL": "Automotive Stampings and Assemblies Limited",
    "ASHAPURMIN": "Ashapura Minechem Limited",
    "ASHIANA": "Ashiana Housing Limited",
    "ASHIMASYN": "Ashima Limited",
    "ASHOKA": "Ashoka Buildcon Limited",
    "ASHOKLEY": "Ashok Leyland Limited",
    "ASIANHOTNR": "Asian Hotels (North) Limited",
    "ASIANPAINT": "Asian Paints Limited",
    "ASIANTILES": "Asian Granito India Limited",
    "ASPINWALL": "Aspinwall and Company Limited",
    "ASTEC": "Astec LifeSciences Limited",
    "ASTERDM": "Aster DM Healthcare Limited",
    "ASTRAL": "Astral Poly Technik Limited",
    "ASTRAMICRO": "Astra Microwave ProductsLimited",
    "ASTRAZEN": "AstraZeneca Pharma India Limited",
    "ASTRON": "AstronPaper& Board Mill Limited",
    "ATFL": "Agro Tech Foods Limited",
    "ATLANTA": "Atlanta  Limited",
    "ATLASCYCLE": "Atlas Cycles (Haryana) Limited",
    "ATUL": "Atul Limited",
    "ATULAUTO": "Atul Auto Limited",
    "AUBANK": "AUSmall Finance BankLimited",
    "AURIONPRO": "Aurionpro Solutions Limited",
    "AUROPHARMA": "Aurobindo PharmaLimited",
    "AUSOMENT": "Ausom Enterprise Limited",
    "AUTOAXLES": "Automotive Axles Limited",
    "AUTOIND": "Autoline Industries Limited",
    "AUTOLITIND": "Autolite (India) Limited",
    "AVADHSUGAR": "AvadhSugar& Energy Limited",
    "AVANTIFEED": "Avanti Feeds Limited",
    "AVTNPL": "AVT Natural Products Limited",
    "AXISBANK": "Axis Bank Limited",
    "AXISCADES": "AXISCADES Engineering Technologies Limited",
    "AYMSYNTEX": "AYM Syntex Limited",
    "BAGFILMS": "B.A.G Films and Media Limited",
    "BAJAJ-AUTO": "Bajaj AutoLimited",
    "BAJAJCON": "Bajaj Consumer Care Limited",
    "BAJAJELEC": "Bajaj ElectricalsLimited",
    "BAJAJFINSV": "Bajaj FinservLimited",
    "BAJAJHIND": "Bajaj Hindusthan Sugar Limited",
    "BAJAJHLDNG": "Bajaj Holdings & Investment Limited",
    "BAJFINANCE": "Bajaj Finance Limited",
    "BALAJITELE": "Balaji Telefilms Limited",
    "BALAMINES": "Balaji Amines Limited",
    "BALAXI": "Balaxi Ventures Limited",
    "BALKRISHNA": "Balkrishna Paper Mills Limited",
    "BALKRISIND": "Balkrishna IndustriesLimited",
    "BALLARPUR": "Ballarpur Industries Limited",
    "BALMLAWRIE": "Balmer Lawrie & Company Limited",
    "BALPHARMA": "Bal Pharma Limited",
    "BALRAMCHIN": "Balrampur Chini Mills Limited",
    "BANARBEADS": "Banaras Beads Limited",
    "BANARISUG": "Bannari Amman Sugars Limited",
    "BANCOINDIA": "Banco Products (I) Limited",
    "BANDHANBNK": "Bandhan Bank Limited",
    "BANG": "Bang Overseas Limited",
    "BANKBARODA": "Bank of Baroda",
    "BANKINDIA": "Bank of India",
    "BANSWRAS": "Banswara Syntex Limited",
    "BARTRONICS": "Bartronics India Limited",
    "BASF": "BASF India Limited",
    "BASML": "Bannari Amman Spinning Mills Limited",
    "BATAINDIA": "Bata India Limited",
    "BAYERCROP": "Bayer Cropscience Limited",
    "BBL": "Bharat Bijlee Limited",
    "BBTC": "Bombay Burmah Trading Corporation Limited",
    "BCG": "Brightcom Group Limited",
    "BCP": "B.C. Power Controls Ltd",
    "BDL": "Bharat Dynamics Limited",
    "BEARDSELL": "Beardsell Limited",
    "BEDMUTHA": "Bedmutha Industries Limited",
    "BEL": "BharatElectronicsLimited",
    "BEML": "BEML Limited",
    "BEPL": "Bhansali Engineering Polymers Limited",
    "BERGEPAINT": "Berger Paints (I) Limited",
    "BFINVEST": "BF Investment Limited",
    "BFUTILITIE": "BF Utilities Limited",
    "BGLOBAL": "Bharatiya Global Infomedia Limited",
    "BGRENERGY": "BGR Energy Systems Limited",
    "BHAGERIA": "Bhageria Industries Limited",
    "BHAGYANGR": "Bhagyanagar IndiaLimited",
    "BHAGYAPROP": "Bhagyanagar Properties Limited",
    "BHANDARI": "Bhandari Hosiery Exports Limited",
    "BHARATFORG": "Bharat Forge Limited",
    "BHARATGEAR": "Bharat Gears Limited",
    "BHARATRAS": "Bharat Rasayan Limited",
    "BHARATWIRE": "Bharat Wire Ropes Limited",
    "BHARTIARTL": "Bharti Airtel Limited",
    "BHEL": "Bharat Heavy Electricals Limited",
    "BIGBLOC": "Bigbloc Construction Limited",
    "BIL": "Bhartiya International Limited",
    "BILENERGY": "Bil Energy Systems Limited",
    "BINDALAGRO": "Oswal Chemicals & Fertilizers Limited",
    "BIOCON": "Biocon Limited",
    "BIOFILCHEM": "Biofil Chemicals & Pharmaceuticals Limited",
    "BIRLACABLE": "Birla Cable Limited",
    "BIRLACORPN": "Birla Corporation Limited",
    "BIRLAMONEY": "Aditya Birla Money Limited",
    "BKMINDST": "Bkm Industries Limited",
    "BLBLIMITED": "BLB Limited",
    "BLISSGVS": "Bliss GVS Pharma Limited",
    "BLKASHYAP": "B. L. Kashyap and Sons Limited",
    "BLS": "BLS International Services Limited",
    "BLUEBLENDS": "Blue Blends (I) Limited",
    "BLUECOAST": "Blue Coast Hotels Limited",
    "BLUEDART": "Blue Dart Express Limited",
    "BLUESTARCO": "Blue Star Limited",
    "BODALCHEM": "Bodal Chemicals Limited",
    "BOMDYEING": "Bombay Dyeing & Mfg Company Limited",
    "BOROSIL": "Borosil Glass Works Limited",
    "BOSCHLTD": "Bosch Limited",
    "BPCL": "Bharat Petroleum Corporation Limited",
    "BPL": "BPL Limited",
    "BRFL": "Bombay Rayon Fashions Limited",
    "BRIGADE": "Brigade Enterprises Limited",
    "BRITANNIA": "Britannia IndustriesLimited",
    "BRNL": "Bharat Road Network Limited",
    "BROOKS": "Brooks Laboratories Limited",
    "BSE": "BSE Limited",
    "BSELINFRA": "BSEL Infrastructure Realty Limited",
    "BSL": "BSL Limited",
    "BSOFT": "BIRLASOFT LIMITED",
    "BURNPUR": "Burnpur Cement Limited",
    "BUTTERFLY": "ButterflyGandhimathi Appliances Limited",
    "BVCL": "Barak Valley Cements Limited",
    "BYKE": "The Byke Hospitality Ltd",
    "CADILAHC": "Cadila Healthcare Limited",
    "CALSOFT": "California Software Company Limited",
    "CAMLINFINE": "Camlin Fine SciencesLimited",
    "CANBK": "Canara Bank",
    "CANDC": "C & C Constructions Limited",
    "CANFINHOME": "Can Fin Homes Limited",
    "CANTABIL": "Cantabil Retail India Limited",
    "CAPACITE": "Capacit’e Infraprojects Limited",
    "CAPLIPOINT": "Caplin Point Laboratories Limited",
    "CAPTRUST": "Capital Trust Limited",
    "CARBORUNIV": "Carborundum Universal Limited",
    "CAREERP": "Career Point Limited",
    "CARERATING": "CARE Ratings Limited",
    "CASTEXTECH": "Castex Technologies Limited",
    "CASTROLIND": "Castrol India Limited",
    "CCHHL": "Country Club Hospitality & Holidays Limited",
    "CCL": "CCL Products (India) Limited",
    "CDSL": "Central Depository Services (India) Limited",
    "CEATLTD": "CEAT Limited",
    "CEBBCO": "Commercial Engineers & Body Builders Co Limited",
    "CELEBRITY": "Celebrity Fashions Limited",
    "CELESTIAL": "Celestial Biolabs Limited",
    "CENTENKA": "Century Enka Limited",
    "CENTEXT": "Century Extrusions Limited",
    "CENTRALBK": "Central Bank of India",
    "CENTRUM": "Centrum Capital Limited",
    "CENTUM": "Centum Electronics Limited",
    "CENTURYPLY": "Century Plyboards (India) Limited",
    "CENTURYTEX": "Century Textiles & Industries Limited",
    "CERA": "Cera Sanitaryware Limited",
    "CEREBRAINT": "Cerebra Integrated Technologies Limited",
    "CESC": "CESC Limited",
    "CESCVENT": "CESC Ventures Limited",
    "CGCL": "Capri Global Capital Limited",
    "CGPOWER": "CG Power and Industrial Solutions Limited",
    "CHALET": "Chalet Hotels Limited",
    "CHAMBLFERT": "Chambal Fertilizers & Chemicals Limited",
    "CHEMFAB": "Chemfab Alkalis Limited",
    "CHENNPETRO": "Chennai Petroleum Corporation Limited",
    "CHOLAFIN": "Cholamandalam Investment andFinance CompanyLimited",
    "CHOLAHLDNG": "Cholamandalam Financial Holdings Limited",
    "CHROMATIC": "Chromatic India Limited",
    "CIGNITITEC": "Cigniti Technologies Limited",
    "CIMMCO": "Cimmco Limited",
    "CINELINE": "Cineline India Limited",
    "CINEVISTA": "Cinevista Limited",
    "CIPLA": "Cipla Limited",
    "CKFSL": "Cox & Kings Financial Service Limited",
    "CLEDUCATE": "CL Educate Limited",
    "CLNINDIA": "Clariant Chemicals (India) Limited",
    "CMICABLES": "CMI Limited",
    "CNOVAPETRO": "CIL Nova Petrochemicals Limited",
    "COALINDIA": "Coal India Limited",
    "COCHINSHIP": "Cochin Shipyard Limited",
    "COFFEEDAY": "CoffeeDay Enterprises Limited",
    "COLPAL": "Colgate Palmolive (India) Limited",
    "COMPINFO": "Compuage Infocom Limited",
    "COMPUSOFT": "Compucom Software Limited",
    "CONCOR": "Container Corporation of India Limited",
    "CONFIPET": "Confidence Petroleum India Limited",
    "CONSOFINVT": "Consolidated Finvest & Holdings Limited",
    "CONTROLPR": "Control Print Limited",
    "CORALFINAC": "Coral India Finance & Housing Limited",
    "CORDSCABLE": "Cords Cable Industries Limited",
    "COROMANDEL": "Coromandel International Limited",
    "CORPBANK": "Corporation Bank",
    "COSMOFILMS": "Cosmo Films Limited",
    "COUNCODOS": "Country Condo’s Limited",
    "COX&KINGS": "Cox & Kings Limited",
    "CREATIVE": "Creative Peripherals and Distribution Limited",
    "CREATIVEYE": "Creative Eye Limited",
    "CREDITACC": "CREDITACCESS GRAMEEN LIMITED",
    "CREST": "Crest Ventures Limited",
    "CRISIL": "CRISIL Limited",
    "CROMPTON": "Crompton GreavesConsumer Electricals Limited",
    "CTE": "Cambridge Technology Enterprises Limited",
    "CUB": "City Union Bank Limited",
    "CUBEXTUB": "Cubex Tubings Limited",
    "CUMMINSIND": "Cummins India Limited",
    "CUPID": "Cupid Limited",
    "CURATECH": "Cura Technologies Limited",
    "CYBERMEDIA": "Cyber Media (India) Limited",
    "CYBERTECH": "Cybertech Systems And Software Limited",
    "CYIENT": "Cyient Limited",
    "DAAWAT": "LT Foods Limited",
    "DABUR": "Dabur IndiaLimited",
    "DALBHARAT": "Dalmia Bharat Limited",
    "DALMIASUG": "Dalmia Bharat Sugar and Industries Limited",
    "DAMODARIND": "Damodar Industries Limited",
    "DATAMATICS": "Datamatics Global Services Limited",
    "DBCORP": "D.B.Corp Limited",
    "DBL": "Dilip Buildcon Limited",
    "DBREALTY": "D B Realty Limited",
    "DBSTOCKBRO": "DB (International) Stock Brokers Limited",
    "DCAL": "Dishman Carbogen Amcis Limited",
    "DCBBANK": "DCB Bank Limited",
    "DCM": "DCM  Limited",
    "DCMFINSERV": "DCM Financial Services Limited",
    "DCMNVL": "DCM Nouvelle Limited",
    "DCMSHRIRAM": "DCM Shriram Limited",
    "DCW": "DCW Limited",
    "DECCANCE": "Deccan Cements Limited",
    "DEEPAKFERT": "Deepak Fertilizers and Petrochemicals Corporation Limited",
    "DEEPAKNTR": "Deepak Nitrite Limited",
    "DEEPIND": "Deep Industries Limited",
    "DELTACORP": "Delta Corp Limited",
    "DELTAMAGNT": "Delta Magnets Limited",
    "DEN": "Den Networks Limited",
    "DENORA": "De Nora India Limited",
    "DFMFOODS": "DFM Foods Limited",
    "DGCONTENT": "DigicontentLimited",
    "DHAMPURSUG": "Dhampur Sugar Mills Limited",
    "DHANBANK": "Dhanlaxmi Bank Limited",
    "DHANUKA": "Dhanuka Agritech Limited",
    "DHARSUGAR": "Dharani Sugars & Chemicals Limited",
    "DHFL": "DewanHousing FinanceCorporation Limited",
    "DHUNINV": "Dhunseri Investments Limited",
    "DIAMONDYD": "Prataap Snacks Limited",
    "DIAPOWER": "Diamond Power Infra Ltd",
    "DICIND": "DIC India Limited",
    "DIGISPICE": "DiGiSPICE Technologies Limited",
    "DIGJAMLTD": "Digjam Limited",
    "DISHTV": "DishTVIndia Limited",
    "DIVISLAB": "Divi’s Laboratories Limited",
    "DIXON": "Dixon Technologies (India) Limited",
    "DLF": "DLF Limited",
    "DLINKINDIA": "D-Link (India) Limited",
    "DMART": "Avenue Supermarts Limited",
    "DNAMEDIA": "Diligent Media Corporation Limited",
    "DOLAT": "Dolat Investments Limited",
    "DOLLAR": "Dollar Industries Limited",
    "DONEAR": "Donear Industries Limited",
    "DPSCLTD": "DPSC Limited",
    "DQE": "DQ Entertainment (International) Limited",
    "DREDGECORP": "Dredging Corporation of India Limited",
    "DRREDDY": "Dr. Reddy’s Laboratories Limited",
    "DSSL": "Dynacons Systems & Solutions Limited",
    "DTIL": "Dhunseri Tea & Industries Limited",
    "DUCON": "Ducon Infratechnologies Limited",
    "DVL": "Dhunseri Ventures Limited",
    "DWARKESH": "Dwarikesh SugarIndustries Limited",
    "DYNAMATECH": "Dynamatic Technologies Limited",
    "DYNPRO": "Dynemic Products Limited",
    "EASTSILK": "Eastern Silk Industries Limited",
    "EASUNREYRL": "Easun Reyrolle Limited",
    "ECLERX": "eClerx Services Limited",
    "EDELWEISS": "Edelweiss Financial Services Limited",
    "EDL": "Empee Distilleries Limited",
    "EDUCOMP": "Educomp Solutions Limited",
    "EICHERMOT": "Eicher MotorsLimited",
    "EIDPARRY": "EID Parry India Limited",
    "EIHAHOTELS": "EIH Associated Hotels Limited",
    "EIHOTEL": "EIH Limited",
    "EIMCOELECO": "Eimco Elecon (India) Limited",
    "EKC": "Everest Kanto Cylinder Limited",
    "ELECON": "EleconEngineering CompanyLimited",
    "ELECTCAST": "Electrosteel Castings Limited",
    "ELECTHERM": "Electrotherm (India) Limited",
    "ELGIEQUIP": "Elgi EquipmentsLimited",
    "ELGIRUBCO": "ElgiRubberCompany Limited",
    "EMAMILTD": "Emami Limited",
    "EMAMIPAP": "Emami Paper Mills Limited",
    "EMAMIREAL": "Emami Realty Limited",
    "EMCO": "Emco Limited",
    "EMKAY": "Emkay Global Financial Services Limited",
    "EMMBI": "Emmbi Industries Limited",
    "ENDURANCE": "Endurance Technologies Limited",
    "ENERGYDEV": "Energy Development Company Limited",
    "ENGINERSIN": "Engineers India Limited",
    "ENIL": "Entertainment Network (India) Limited",
    "EON": "Eon Electric Limited",
    "EQUITAS": "Equitas Holdings Limited",
    "ERIS": "Eris Lifesciences Limited",
    "EROSMEDIA": "Eros International Media Limited",
    "ESABINDIA": "Esab India Limited",
    "ESCORTS": "EscortsLimited",
    "ESSARSHPNG": "Essar Shipping Limited",
    "ESSELPACK": "Essel Propack Limited",
    "ESTER": "Ester Industries Limited",
    "EUROCERA": "Euro Ceramics Limited",
    "EUROMULTI": "Euro Multivision Limited",
    "EUROTEXIND": "Eurotex Industries and Exports Limited",
    "EVEREADY": "Eveready Industries India Limited",
    "EVERESTIND": "Everest Industries Limited",
    "EXCEL": "Excel Realty N Infra Limited",
    "EXCELINDUS": "Excel Industries Limited",
    "EXIDEIND": "Exide Industries Limited",
    "EXPLEOSOL": "Expleo Solutions Limited",
    "FACT": "Fertilizers and Chemicals Travancore Limited",
    "FAIRCHEM": "Fairchem Speciality Limited",
    "FCL": "Fineotex Chemical Limited",
    "FCONSUMER": "Future Consumer Limited",
    "FCSSOFT": "FCS Software Solutions Limited",
    "FDC": "FDC Limited",
    "FEDERALBNK": "The Federal Bank Limited",
    "FEL": "Future Enterprises Limited",
    "FELDVR": "Future Enterprises Limited",
    "FIEMIND": "Fiem Industries Limited",
    "FILATEX": "Filatex India Limited",
    "FINCABLES": "Finolex Cables Limited",
    "FINEORG": "Fine Organic Industries Limited",
    "FINPIPE": "Finolex IndustriesLimited",
    "FLEXITUFF": "Flexituff Ventures International Limited",
    "FLFL": "Future Lifestyle Fashions Limited",
    "FLUOROCHEM": "Gujarat Fluorochemicals Limited",
    "FMGOETZE": "Federal-Mogul Goetze (India) Limited.",
    "FMNL": "Future Market Networks Limited",
    "FORCEMOT": "FORCE MOTORS LTD",
    "FORTIS": "Fortis Healthcare Limited",
    "FOSECOIND": "Foseco India Limited",
    "FRETAIL": "Future Retail Limited",
    "FSC": "Future Supply Chain Solutions Limited",
    "FSL": "Firstsource Solutions Limited",
    "GABRIEL": "Gabriel India Limited",
    "GAEL": "Gujarat Ambuja Exports Limited",
    "GAIL": "GAIL (India) Limited",
    "GAL": "Gyscoal Alloys Limited",
    "GALAXYSURF": "Galaxy Surfactants Limited",
    "GALLANTT": "Gallantt Metal Limited",
    "GALLISPAT": "Gallantt Ispat Limited",
    "GAMMNINFRA": "Gammon Infrastructure Projects Limited",
    "GANDHITUBE": "Gandhi Special Tubes Limited",
    "GANECOS": "Ganesha Ecosphere Limited",
    "GANESHHOUC": "Ganesh Housing Corporation Limited",
    "GANGESSECU": "Ganges Securities Limited",
    "GANGOTRI": "Gangotri Textiles Limited",
    "GARDENSILK": "Garden Silk Mills Limited",
    "GARFIBRES": "Garware Technical Fibres Limited",
    "GATI": "GATI Limited",
    "GAYAHWS": "Gayatri Highways Limited",
    "GAYAPROJ": "Gayatri Projects Limited",
    "GDL": "Gateway Distriparks Limited",
    "GEECEE": "GeeCee Ventures Limited",
    "GENESYS": "Genesys International Corporation Limited",
    "GENUSPAPER": "Genus Paper & Boards Limited",
    "GENUSPOWER": "Genus Power Infrastructures Limited",
    "GEOJITFSL": "Geojit Financial Services Limited",
    "GEPIL": "GE Power India Limited",
    "GESHIP": "The Great EasternShipping CompanyLimited",
    "GET&D": "GE T&D India Limited",
    "GFLLIMITED": "GFL Limited",
    "GHCL": "GHCL Limited",
    "GICHSGFIN": "GIC Housing Finance Limited",
    "GICRE": "General Insurance Corporation of India",
    "GILLANDERS": "Gillanders Arbuthnot & Company Limited",
    "GILLETTE": "Gillette India Limited",
    "GINNIFILA": "Ginni Filaments Limited",
    "GIPCL": "Gujarat IndustriesPower CompanyLimited",
    "GISOLUTION": "GI Engineering Solutions Limited",
    "GKWLIMITED": "GKW Limited",
    "GLAXO": "GlaxoSmithKline Pharmaceuticals Limited",
    "GLENMARK": "Glenmark Pharmaceuticals Limited",
    "GLFL": "Gujarat Lease Financing Limited",
    "GLOBALVECT": "Global Vectra Helicorp Limited",
    "GLOBOFFS": "Global Offshore Services Limited",
    "GLOBUSSPR": "Globus Spirits Limited",
    "GMBREW": "GM Breweries Limited",
    "GMDCLTD": "Gujarat Mineral Development Corporation Limited",
    "GMMPFAUDLR": "GMM Pfaudler Limited",
    "GMRINFRA": "GMR Infrastructure Limited",
    "GNA": "GNA Axles Limited",
    "GNFC": "Gujarat Narmada Valley Fertilizers and Chemicals Limited",
    "GOACARBON": "Goa Carbon Limited",
    "GOCLCORP": "GOCL Corporation Limited",
    "GODFRYPHLP": "Godfrey Phillips India Limited",
    "GODREJAGRO": "Godrej Agrovet Limited",
    "GODREJCP": "Godrej Consumer Products Limited",
    "GODREJIND": "Godrej Industries Limited",
    "GODREJPROP": "Godrej Properties Limited",
    "GOENKA": "Goenka Diamond and Jewels Limited",
    "GOKEX": "Gokaldas ExportsLimited",
    "GOKUL": "Gokul Refoils and Solvent Limited",
    "GOKULAGRO": "Gokul Agro Resources Limited",
    "GOLDENTOBC": "Golden Tobacco Limited",
    "GOLDIAM": "Goldiam International Limited",
    "GOLDTECH": "Goldstone Technologies Limited",
    "GOODLUCK": "Goodluck India Limited",
    "GPIL": "Godawari Power And Ispat limited",
    "GPPL": "Gujarat Pipavav Port Limited",
    "GPTINFRA": "GPT Infraprojects Limited",
    "GRANULES": "Granules India Limited",
    "GRAPHITE": "Graphite IndiaLimited",
    "GRASIM": "Grasim IndustriesLimited",
    "GRAVITA": "Gravita India Limited",
    "GREAVESCOT": "Greaves Cotton Limited",
    "GREENLAM": "Greenlam Industries Limited",
    "GREENPANEL": "Greenpanel Industries Limited",
    "GREENPLY": "Greenply Industries Limited",
    "GREENPOWER": "Orient Green Power Company Limited",
    "GRINDWELL": "Grindwell Norton Limited",
    "GROBTEA": "The GrobTea CompanyLimited",
    "GRPLTD": "GRP Limited",
    "GRSE": "Garden Reach Shipbuilders & Engineers Limited",
    "GSCLCEMENT": "Gujarat Sidhee Cement Limited",
    "GSFC": "Gujarat State Fertilizers & Chemicals Limited",
    "GSKCONS": "GlaxoSmithKline Consumer Healthcare Limited",
    "GSPL": "Gujarat State Petronet Limited",
    "GSS": "GSS Infotech Limited",
    "GTL": "GTL Limited",
    "GTLINFRA": "GTL Infrastructure Limited",
    "GTNIND": "GTN Industries Limited",
    "GTNTEX": "GTN Textiles Limited",
    "GTPL": "GTPL Hathway Limited",
    "GUFICBIO": "Gufic Biosciences Limited",
    "GUJALKALI": "Gujarat Alkalies and Chemicals Limited",
    "GUJAPOLLO": "Gujarat Apollo Industries Limited",
    "GUJGASLTD": "Gujarat Gas Limited",
    "GUJRAFFIA": "Gujarat Raffia Industries Limited",
    "GULFOILLUB": "Gulf OilLubricantsIndia Limited",
    "GULFPETRO": "GP Petroleums Limited",
    "GULPOLY": "Gulshan Polyols Limited",
    "GVKPIL": "GVK Power & Infrastructure Limited",
    "HAL": "Hindustan Aeronautics Limited",
    "HARITASEAT": "Harita Seating Systems Limited",
    "HARRMALAYA": "Harrisons  Malayalam Limited",
    "HATHWAY": "Hathway Cable & Datacom Limited",
    "HATSUN": "Hatsun Agro Product Limited",
    "HAVELLS": "Havells IndiaLimited",
    "HAVISHA": "Sri Havisha Hospitality and Infrastructure Limited",
    "HBLPOWER": "HBL Power Systems Limited",
    "HBSL": "HB Stockholdings Limited",
    "HCC": "HindustanConstruction CompanyLimited",
    "HCG": "Healthcare Global Enterprises Limited",
    "HCL-INSYS": "HCL Infosystems Limited",
    "HCLTECH": "HCL Technologies Limited",
    "HDFC": "Housing Development Finance Corporation Limited",
    "HDFCAMC": "HDFC Asset ManagementCompany Limited",
    "HDFCBANK": "HDFC Bank Limited",
    "HDFCLIFE": "HDFC LifeInsurance CompanyLimited",
    "HDIL": "Housing Development and Infrastructure Limited",
    "HEG": "HEG Limited",
    "HEIDELBERG": "HeidelbergCement India Limited",
    "HERCULES": "Hercules Hoists Limited",
    "HERITGFOOD": "Heritage Foods Limited",
    "HEROMOTOCO": "Hero MotoCorpLimited",
    "HESTERBIO": "Hester Biosciences Limited",
    "HEXATRADEX": "Hexa Tradex Limited",
    "HEXAWARE": "Hexaware Technologies Limited",
    "HFCL": "HFCL Limited",
    "HGINFRA": "H.G. Infra Engineering Limited",
    "HGS": "Hinduja Global Solutions Limited",
    "HIKAL": "Hikal Limited",
    "HIL": "HIL Limited",
    "HILTON": "Hilton Metal Forging Limited",
    "HIMATSEIDE": "Himatsingka Seide Limited",
    "HINDALCO": "Hindalco IndustriesLimited",
    "HINDCOMPOS": "Hindustan Composites Limited",
    "HINDCOPPER": "HindustanCopperLimited",
    "HINDMOTORS": "Hindustan Motors Limited",
    "HINDNATGLS": "Hindusthan National Glass & Industries Limited",
    "HINDOILEXP": "Hindustan Oil Exploration Company Limited",
    "HINDPETRO": "Hindustan Petroleum Corporation Limited",
    "HINDSYNTEX": "Hind Syntex Limited",
    "HINDUNILVR": "Hindustan UnileverLimited",
    "HINDZINC": "HindustanZincLimited",
    "HIRECT": "Hind Rectifiers Limited",
    "HISARMETAL": "Hisar Metal Industries Limited",
    "HITECH": "Hi-Tech Pipes Limited",
    "HITECHCORP": "Hitech Corporation Limited",
    "HITECHGEAR": "The Hi-Tech Gears Limited",
    "HMT": "HMT Limited",
    "HMVL": "Hindustan Media Ventures Limited",
    "HNDFDS": "Hindustan Foods Limited",
    "HONAUT": "Honeywell Automation India Limited",
    "HONDAPOWER": "Honda Siel Power Products Limited",
    "HOTELEELA": "Hotel Leela Venture Limited",
    "HOTELRUGBY": "Hotel Rugby Limited",
    "HOVS": "HOV Services Limited",
    "HPL": "HPL Electric & Power Limited",
    "HSCL": "Himadri Speciality Chemical Limited",
    "HSIL": "HSIL Limited",
    "HTMEDIA": "HT Media Limited",
    "HUBTOWN": "Hubtown Limited",
    "HUDCO": "Housing & Urban Development Corporation Limited",
    "IBREALEST": "Indiabulls Real Estate Limited",
    "IBULHSGFIN": "Indiabulls Housing Finance Limited",
    "IBULISL": "Indiabulls Integrated Services Limited",
    "IBVENTURES": "Indiabulls Ventures Limited",
    "ICICIBANK": "ICICI Bank Limited",
    "ICICIGI": "ICICI Lombard General Insurance Company Limited",
    "ICICIPRULI": "ICICI Prudential Life Insurance Company Limited",
    "ICIL": "Indo Count Industries Limited",
    "ICRA": "ICRA Limited",
    "IDBI": "IDBI Bank Limited",
    "IDEA": "Vodafone IdeaLimited",
    "IDFC": "IDFC Limited",
    "IDFCFIRSTB": "IDFC First Bank Limited",
    "IEX": "Indian Energy Exchange Limited",
    "IFBAGRO": "IFB Agro Industries Limited",
    "IFBIND": "IFB Industries Limited",
    "IFCI": "IFCILimited",
    "IFGLEXPOR": "IFGL Refractories Limited",
    "IGARASHI": "Igarashi Motors India Limited",
    "IGL": "Indraprastha Gas Limited",
    "IGPL": "IG PetrochemicalsLimited",
    "IIFL": "IIFL Finance Limited",
    "IIFLSEC": "IIFL Securities Limited",
    "IIFLWAM": "Iifl Wealth Management Limited",
    "IITL": "Industrial Investment Trust Limited",
    "IL&FSENGG": "IL&FS Engineering and Construction Company Limited",
    "IL&FSTRANS": "IL&FSTransportationNetworks Limited",
    "IMFA": "Indian Metals & Ferro Alloys Limited",
    "IMPAL": "India Motor Parts and Accessories Limited",
    "IMPEXFERRO": "Impex Ferro Tech Limited",
    "INDBANK": "Indbank Merchant Banking Services Limited",
    "INDHOTEL": "The Indian Hotels Company Limited",
    "INDIACEM": "The India Cements Limited",
    "INDIAGLYCO": "India Glycols Limited",
    "INDIAMART": "Indiamart IntermeshLimited",
    "INDIANB": "Indian Bank",
    "INDIANCARD": "Indian Card Clothing Company Limited",
    "INDIANHUME": "Indian HumePipeCompany Limited",
    "INDIGO": "InterGlobe Aviation Limited",
    "INDLMETER": "IMP Powers Limited",
    "INDNIPPON": "India Nippon ElectricalsLimited",
    "INDOCO": "Indoco Remedies Limited",
    "INDORAMA": "Indo Rama Synthetics (India) Limited",
    "INDOSOLAR": "Indosolar Limited",
    "INDOSTAR": "IndoStar Capital Finance Limited",
    "INDOTECH": "Indo Tech Transformers Limited",
    "INDOTHAI": "Indo Thai Securities Limited",
    "INDOWIND": "Indowind Energy Limited",
    "INDRAMEDCO": "Indraprastha Medical Corporation Limited",
    "INDSWFTLAB": "Ind-Swift Laboratories Limited",
    "INDSWFTLTD": "Ind-Swift Limited",
    "INDTERRAIN": "Indian Terrain Fashions Limited",
    "INDUSINDBK": "IndusInd Bank Limited",
    "INEOSSTYRO": "INEOS Styrolution India Limited",
    "INFIBEAM": "Infibeam Avenues Limited",
    "INFOBEAN": "InfoBeans Technologies Limited",
    "INFRATEL": "Bharti InfratelLimited",
    "INFY": "Infosys Limited",
    "INGERRAND": "Ingersoll Rand (India) Limited",
    "INOXLEISUR": "INOX Leisure Limited",
    "INOXWIND": "Inox Wind Limited",
    "INSECTICID": "Insecticides (India) Limited",
    "INSPIRISYS": "Inspirisys Solutions Limited",
    "INTEGRA": "Integra Garments and Textiles Limited",
    "INTELLECT": "Intellect Design Arena Limited",
    "INTENTECH": "Intense Technologies Limited",
    "INVENTURE": "Inventure Growth & Securities Limited",
    "IOB": "Indian Overseas Bank",
    "IOC": "Indian Oil CorporationLimited",
    "IOLCP": "IOL Chemicals and Pharmaceuticals Limited",
    "IPAPPM": "International Paper APPM Limited",
    "IPCALAB": "IPCA Laboratories Limited",
    "IRB": "IRB Infrastructure Developers Limited",
    "IRCON": "Ircon International Limited",
    "IRCTC": "Indian Railway Catering And Tourism Corporation Limited",
    "ISEC": "ICICI SecuritiesLimited",
    "ISFT": "Intrasoft Technologies Limited",
    "ISMTLTD": "ISMT Limited",
    "ITC": "ITC Limited",
    "ITDC": "India Tourism Development Corporation Limited",
    "ITDCEM": "ITD Cementation India Limited",
    "ITI": "ITI Limited",
    "IVC": "IL&FS Investment Managers Limited",
    "IVP": "IVP Limited",
    "IVRCLINFRA": "IVRCL Limited",
    "IZMO": "IZMO Limited",
    "J&KBANK": "The Jammu & Kashmir Bank Limited",
    "JAGRAN": "Jagran Prakashan Limited",
    "JAGSNPHARM": "Jagsonpal Pharmaceuticals Limited",
    "JAIBALAJI": "Jai Balaji Industries Limited",
    "JAICORPLTD": "Jai Corp Limited",
    "JAIHINDPRO": "Jaihind Projects Limited",
    "JAINSTUDIO": "Jain Studios Limited",
    "JAMNAAUTO": "Jamna Auto Industries Limited",
    "JASH": "Jash Engineering Limited",
    "JAYAGROGN": "Jayant Agro Organics Limited",
    "JAYBARMARU": "Jay Bharat Maruti Limited",
    "JAYNECOIND": "Jayaswal Neco Industries Limited",
    "JAYSREETEA": "Jayshree Tea & Industries Limited",
    "JBCHEPHARM": "JB Chemicals & Pharmaceuticals Limited",
    "JBFIND": "JBF Industries Limited",
    "JBMA": "JBM Auto Limited",
    "JCHAC": "Johnson Controls – Hitachi Air Conditioning India Limited",
    "JETAIRWAYS": "Jet Airways (India) Limited",
    "JHS": "JHS Svendgaard Laboratories Limited",
    "JIKIND": "JIK Industries Limited",
    "JINDALPHOT": "Jindal Photo Limited",
    "JINDALPOLY": "Jindal Poly Films Limited",
    "JINDALSAW": "Jindal Saw Limited",
    "JINDALSTEL": "Jindal Steel & Power Limited",
    "JINDCOT": "Jindal Cotex Limited",
    "JINDRILL": "Jindal Drilling And Industries Limited",
    "JINDWORLD": "Jindal Worldwide Limited",
    "JISLDVREQS": "Jain Irrigation Systems Limited",
    "JISLJALEQS": "Jain Irrigation Systems Limited",
    "JITFINFRA": "JITF Infralogistics Limited",
    "JIYAECO": "Jiya Eco-Products Limited",
    "JKCEMENT": "JK Cement Limited",
    "JKIL": "J.Kumar Infraprojects Limited",
    "JKLAKSHMI": "JK Lakshmi Cement Limited",
    "JKPAPER": "JK Paper Limited",
    "JKTYRE": "JKTyre& Industries Limited",
    "JMA": "Jullundur Motor Agency (Delhi) Limited",
    "JMCPROJECT": "JMC Projects (India) Limited",
    "JMFINANCIL": "JM Financial Limited",
    "JMTAUTOLTD": "JMT Auto Limited",
    "JOCIL": "Jocil Limited",
    "JPASSOCIAT": "Jaiprakash Associates Limited",
    "JPINFRATEC": "Jaypee Infratech Limited",
    "JPOLYINVST": "Jindal Poly Investment and Finance Company Limited",
    "JPPOWER": "Jaiprakash Power Ventures Limited",
    "JSL": "Jindal Stainless Limited",
    "JSLHISAR": "Jindal Stainless (Hisar) Limited",
    "JSWENERGY": "JSW Energy Limited",
    "JSWHL": "JSW Holdings Limited",
    "JSWSTEEL": "JSW SteelLimited",
    "JTEKTINDIA": "Jtekt India Limited",
    "JUBILANT": "Jubilant Life Sciences Limited",
    "JUBLFOOD": "Jubilant FoodworksLimited",
    "JUBLINDS": "Jubilant Industries Limited",
    "JUMPNET": "Jump Networks Limited",
    "JUSTDIAL": "Just Dial Limited",
    "JVLAGRO": "JVL Agro Industries Limited",
    "JYOTHYLAB": "Jyothy Labs Limited",
    "KABRAEXTRU": "Kabra Extrusion Technik Limited",
    "KAJARIACER": "Kajaria Ceramics Limited",
    "KAKATCEM": "Kakatiya Cement Sugar & Industries Limited",
    "KALPATPOWR": "Kalpataru Power Transmission Limited",
    "KALYANI": "Kalyani Commercials Limited",
    "KALYANIFRG": "Kalyani Forge Limited",
    "KAMATHOTEL": "Kamat Hotels (I) Limited",
    "KAMDHENU": "Kamdhenu Limited",
    "KANANIIND": "Kanani Industries Limited",
    "KANORICHEM": "Kanoria Chemicals & Industries Limited",
    "KANSAINER": "Kansai Nerolac Paints Limited",
    "KARDA": "Karda Constructions Limited",
    "KARMAENG": "Karma Energy Limited",
    "KARURVYSYA": "Karur Vysya Bank Limited",
    "KAUSHALYA": "Kaushalya Infrastructure Development Corporation Limited",
    "KAVVERITEL": "KavveriTelecomProducts Limited",
    "KAYA": "Kaya Limited",
    "KCP": "KCP Limited",
    "KCPSUGIND": "KCP Sugar and Industries Corporation Limited",
    "KDDL": "KDDL Limited",
    "KEC": "KEC InternationalLimited",
    "KECL": "Kirloskar Electric Company Limited",
    "KEI": "KEI Industries Limited",
    "KELLTONTEC": "Kellton Tech Solutions Limited",
    "KENNAMET": "Kennametal India Limited",
    "KERNEX": "Kernex Microsystems (India) Limited",
    "KESARENT": "Kesar Enterprises Limited",
    "KESORAMIND": "Kesoram Industries Limited",
    "KEYFINSERV": "Keynote Financial Services Limited",
    "KGL": "Karuturi Global Limited",
    "KHADIM": "Khadim India Limited",
    "KHAITANLTD": "Khaitan (India) Limited",
    "KHANDSE": "Khandwala Securities Limited",
    "KICL": "Kalyani Investment Company Limited",
    "KILITCH": "Kilitch Drugs (India) Limited",
    "KINGFA": "Kingfa Science & Technology (India) Limited",
    "KIOCL": "KIOCL Limited",
    "KIRIINDUS": "Kiri Industries Limited",
    "KIRLOSBROS": "Kirloskar Brothers Limited",
    "KIRLOSENG": "Kirloskar Oil Engines Limited",
    "KIRLOSIND": "Kirloskar Industries Limited",
    "KITEX": "Kitex Garments Limited",
    "KKCL": "Kewal Kiran Clothing Limited",
    "KMSUGAR": "K.M.Sugar Mills Limited",
    "KNRCON": "KNR Constructions Limited",
    "KOHINOOR": "Kohinoor Foods Limited",
    "KOKUYOCMLN": "Kokuyo Camlin Limited",
    "KOLTEPATIL": "Kolte - Patil Developers Limited",
    "KOPRAN": "Kopran Limited",
    "KOTAKBANK": "Kotak Mahindra BankLimited",
    "KOTARISUG": "Kothari Sugars And Chemicals Limited",
    "KOTHARIPET": "Kothari Petrochemicals Limited",
    "KOTHARIPRO": "Kothari Products Limited",
    "KPITTECH": "KPIT Technologies Limited",
    "KPRMILL": "K.P.R. Mill Limited",
    "KRBL": "KRBLLimited",
    "KREBSBIO": "Krebs Biochemicals and Industries Limited",
    "KRIDHANINF": "Kridhan Infra Limited",
    "KRISHANA": "Krishana Phoschem Limited",
    "KSB": "Ksb Limited",
    "KSCL": "KaveriSeed CompanyLimited",
    "KSERASERA": "KSS Limited",
    "KSK": "KSK Energy Ventures Limited",
    "KSL": "Kalyani Steels Limited",
    "KTIL": "Kesar Terminals & Infrastructure Limited",
    "KTKBANK": "The Karnataka Bank Limited",
    "KUANTUM": "Kuantum Papers Limited",
    "KWALITY": "kwality limited",
    "L&TFH": "L&T Finance Holdings Limited",
    "LAKPRE": "Lakshmi Precision Screws Limited",
    "LAKSHVILAS": "Lakshmi Vilas Bank Limited",
    "LALPATHLAB": "Dr. Lal Path Labs Ltd.",
    "LAMBODHARA": "Lambodhara Textiles Limited",
    "LAOPALA": "La Opala RG Limited",
    "LASA": "Lasa Supergenerics Limited",
    "LAURUSLABS": "Laurus Labs Limited",
    "LAXMIMACH": "Lakshmi Machine WorksLimited",
    "LEMONTREE": "Lemon Tree Hotels Limited",
    "LFIC": "Lakshmi Finance & Industrial Corporation Limited",
    "LGBBROSLTD": "LG Balakrishnan & Bros Limited",
    "LGBFORGE": "LGB Forge Limited",
    "LIBAS": "Libas Designs Limited",
    "LIBERTSHOE": "Liberty Shoes Limited",
    "LICHSGFIN": "LIC Housing Finance Limited",
    "LINCOLN": "Lincoln Pharmaceuticals Limited",
    "LINCPEN": "Linc Pen & Plastics Limited",
    "LINDEINDIA": "Linde India Limited",
    "LOKESHMACH": "Lokesh Machines Limited",
    "LOTUSEYE": "Lotus Eye Hospital and Institute Limited",
    "LOVABLE": "Lovable Lingerie Limited",
    "LPDC": "Landmark Property Development Company Limited",
    "LSIL": "Lloyds Steels Industries Limited",
    "LT": "Larsen & Toubro Limited",
    "LTI": "Larsen & Toubro Infotech Limited",
    "LTTS": "L&T Technology Services Limited",
    "LUMAXIND": "Lumax Industries Limited",
    "LUMAXTECH": "Lumax Auto Technologies Limited",
    "LUPIN": "LupinLimited",
    "LUXIND": "Lux Industries Limited",
    "LYKALABS": "Lyka Labs Limited",
    "LYPSAGEMS": "Lypsa Gems & Jewellery Limited",
    "M&M": "Mahindra & MahindraLimited",
    "M&MFIN": "Mahindra & Mahindra Financial Services Limited",
    "MAANALU": "MaanAluminiumLimited",
    "MADHAV": "Madhav Marbles and Granites Limited",
    "MADHUCON": "Madhucon Projects Limited",
    "MADRASFERT": "Madras Fertilizers Limited",
    "MAGADSUGAR": "Magadh Sugar & Energy Limited",
    "MAGMA": "Magma Fincorp Limited",
    "MAGNUM": "Magnum Ventures Limited",
    "MAHABANK": "Bank of Maharashtra",
    "MAHAPEXLTD": "Maha Rashtra Apex Corporation Limited",
    "MAHASTEEL": "Mahamaya Steel Industries Limited",
    "MAHESHWARI": "Maheshwari Logistics Limited",
    "MAHINDCIE": "Mahindra CIE Automotive Limited",
    "MAHLIFE": "Mahindra Lifespace Developers Limited",
    "MAHLOG": "Mahindra Logistics Limited",
    "MAHSCOOTER": "Maharashtra Scooters Limited",
    "MAHSEAMLES": "Maharashtra Seamless Limited",
    "MAITHANALL": "Maithan Alloys Limited",
    "MAJESCO": "Majesco Limited",
    "MALUPAPER": "Malu Paper Mills Limited",
    "MANAKALUCO": "Manaksia Aluminium Company Limited",
    "MANAKCOAT": "Manaksia Coated Metals & Industries Limited",
    "MANAKSIA": "Manaksia Limited",
    "MANAKSTEEL": "Manaksia Steels Limited",
    "MANALIPETC": "Manali Petrochemicals Limited",
    "MANAPPURAM": "Manappuram Finance Limited",
    "MANGALAM": "Mangalam Drugs And Organics Limited",
    "MANGCHEFER": "Mangalore Chemicals & Fertilizers Limited",
    "MANGLMCEM": "Mangalam Cement Limited",
    "MANGTIMBER": "Mangalam Timber Products Limited",
    "MANINDS": "Man Industries (India) Limited",
    "MANINFRA": "Man Infraconstruction Limited",
    "MANPASAND": "Manpasand Beverages Limited",
    "MANUGRAPH": "Manugraph India Limited",
    "MARALOVER": "Maral Overseas Limited",
    "MARATHON": "Marathon Nextgen Realty Limited",
    "MARICO": "MaricoLimited",
    "MARKSANS": "Marksans Pharma Limited",
    "MARUTI": "Maruti Suzuki IndiaLimited",
    "MASFIN": "MAS Financial ServicesLimited",
    "MASKINVEST": "Mask Investments Limited",
    "MASTEK": "Mastek Limited",
    "MATRIMONY": "Matrimony.Com Limited",
    "MAWANASUG": "Mawana Sugars Limited",
    "MAXINDIA": "Max India Limited",
    "MAXVIL": "Max Ventures and Industries Limited",
    "MAYURUNIQ": "Mayur Uniquoters Ltd",
    "MAZDA": "Mazda Limited",
    "MBAPL": "Madhya Bharat Agro Products Limited",
    "MBECL": "Mcnally Bharat Engineering Company Limited",
    "MBLINFRA": "MBL Infrastructures Limited",
    "MCDHOLDING": "McDowell Holdings Limited",
    "MCDOWELL-N": "United Spirits Limited",
    "MCLEODRUSS": "Mcleod Russel India Limited",
    "MCX": "Multi Commodity Exchange of India Limited",
    "MEGASOFT": "Megasoft Limited",
    "MEGH": "Meghmani OrganicsLimited",
    "MELSTAR": "Melstar Information Technologies Limited",
    "MENONBE": "Menon Bearings Limited",
    "MEP": "MEP Infrastructure Developers Limited",
    "MERCATOR": "Mercator Limited",
    "METALFORGE": "MetalystForgingsLimited",
    "METKORE": "Metkore Alloys & Industries Limited",
    "METROPOLIS": "Metropolis Healthcare Limited",
    "MFSL": "Max Financial Services Limited",
    "MGL": "Mahanagar Gas Limited",
    "MHRIL": "Mahindra Holidays & Resorts India Limited",
    "MIC": "MIC Electronics Limited",
    "MIDHANI": "Mishra Dhatu Nigam Limited",
    "MINDACORP": "Minda Corporation Limited",
    "MINDAIND": "Minda Industries Limited",
    "MINDTECK": "Mindteck (India) Limited",
    "MINDTREE": "MindTreeLimited",
    "MIRCELECTR": "MIRC Electronics Limited",
    "MIRZAINT": "Mirza International Limited",
    "MMFL": "MM Forgings Limited",
    "MMTC": "MMTC Limited",
    "MODIRUBBER": "Modi Rubber Limited",
    "MOHITIND": "Mohit Industries Limited",
    "MOHOTAIND": "Mohota Industries Limited",
    "MOIL": "MOIL Limited",
    "MOLDTECH": "Mold-Tek Technologies Limited",
    "MOLDTKPAC": "Mold-Tek Packaging Limited",
    "MONTECARLO": "Monte Carlo Fashions Limited",
    "MORARJEE": "Morarjee Textiles Limited",
    "MOREPENLAB": "Morepen Laboratories Limited",
    "MOTHERSUMI": "Motherson Sumi SystemsLimited",
    "MOTILALOFS": "Motilal Oswal Financial Services Limited",
    "MOTOGENFIN": "The Motor & General Finance Limited",
    "MPHASIS": "MphasiSLimited",
    "MPSLTD": "MPS Limited",
    "MRF": "MRF Limited",
    "MRO-TEK": "MRO-TEK Realty Limited",
    "MRPL": "MangaloreRefineryand Petrochemicals Limited",
    "MSPL": "MSP Steel & Power Limited",
    "MSTCLTD": "Mstc Limited",
    "MTEDUCARE": "MT Educare Limited",
    "MTNL": "Mahanagar Telephone Nigam Limited",
    "MUKANDENGG": "Mukand Engineers Limited",
    "MUKANDLTD": "Mukand Limited",
    "MUKTAARTS": "Mukta Arts Limited",
    "MUNJALAU": "Munjal Auto Industries Limited",
    "MUNJALSHOW": "Munjal Showa Limited",
    "MURUDCERA": "Murudeshwar Ceramics Limited",
    "MUTHOOTCAP": "Muthoot Capital Services Limited",
    "MUTHOOTFIN": "Muthoot Finance Limited",
    "MVL": "MVL Limited",
    "NACLIND": "NACL Industries Limited",
    "NAGAFERT": "Nagarjuna Fertilizers and Chemicals Limited",
    "NAGAROIL": "Nagarjuna Oil Refinery Limited",
    "NAGREEKCAP": "Nagreeka Capital & Infrastructure Limited",
    "NAGREEKEXP": "Nagreeka Exports Limited",
    "NAHARCAP": "NaharCapital and Financial Services Limited",
    "NAHARINDUS": "Nahar Industrial Enterprises Limited",
    "NAHARPOLY": "Nahar Poly Films Limited",
    "NAHARSPING": "Nahar Spinning Mills Limited",
    "NATCOPHARM": "Natco Pharma Limited",
    "NATHBIOGEN": "Nath Bio-Genes (India) Limited",
    "NATIONALUM": "National Aluminium Company Limited",
    "NATNLSTEEL": "National Steel And Agro Industries Limited",
    "NAUKRI": "Info Edge (India) Limited",
    "NAVINFLUOR": "Navin Fluorine International Limited",
    "NAVKARCORP": "Navkar Corporation Limited",
    "NAVNETEDUL": "Navneet Education Limited",
    "NBCC": "NBCC (India) Limited",
    "NBIFIN": "N. B. I. Industrial Finance Company Limited",
    "NBVENTURES": "Nava Bharat Ventures Limited",
    "NCC": "NCC Limited",
    "NCLIND": "NCL Industries Limited",
    "NDGL": "Naga Dhunseri Group Limited",
    "NDL": "Nandan Denim Limited",
    "NDTV": "New Delhi Television Limited",
    "NECCLTD": "North Eastern Carrying Corporation Limited",
    "NECLIFE": "Nectar LifesciencesLimited",
    "NELCAST": "Nelcast Limited",
    "NELCO": "NELCO Limited",
    "NEOGEN": "Neogen Chemicals Limited",
    "NESCO": "Nesco Limited",
    "NESTLEIND": "Nestle India Limited",
    "NETWORK18": "Network18 Media & Investments Limited",
    "NEULANDLAB": "Neuland Laboratories Limited",
    "NEWGEN": "Newgen Software Technologies Limited",
    "NEXTMEDIA": "Next Mediaworks Limited",
    "NFL": "National Fertilizers Limited",
    "NH": "Narayana Hrudayalaya Ltd.",
    "NHPC": "NHPC Limited",
    "NIACL": "The New India Assurance Company Limited",
    "NIBL": "NRB Industrial Bearings Limited",
    "NIITLTD": "NIITLimited",
    "NIITTECH": "NIIT Technologies Limited",
    "NILAINFRA": "Nila Infrastructures Limited",
    "NILASPACES": "Nila Spaces Limited",
    "NILKAMAL": "Nilkamal Limited",
    "NIPPOBATRY": "Indo-National Limited",
    "NIRAJISPAT": "Niraj Ispat Industries Limited",
    "NITCO": "Nitco Limited",
    "NITINFIRE": "Nitin Fire Protection Industries Limited",
    "NITINSPIN": "Nitin Spinners Limited",
    "NKIND": "NK Industries Limited",
    "NLCINDIA": "NLC India Limited",
    "NMDC": "NMDC Limited",
    "NOCIL": "NOCIL Limited",
    "NOIDATOLL": "Noida Toll Bridge Company Limited",
    "NORBTEAEXP": "Norben Tea & Exports Limited",
    "NRAIL": "N R Agarwal Industries Limited",
    "NRBBEARING": "NRB Bearing Limited",
    "NSIL": "Nalwa Sons Investments Limited",
    "NTL": "Neueon Towers Limited",
    "NTPC": "NTPC Limited",
    "NUCLEUS": "Nucleus Software Exports Limited",
    "NXTDIGITAL": "NXTDIGITAL LIMITED",
    "OAL": "Oriental Aromatics Limited",
    "OBEROIRLTY": "Oberoi Realty Limited",
    "OCCL": "Oriental Carbon & Chemicals Limited",
    "OFSS": "Oracle Financial Services Software Limited",
    "OIL": "Oil India Limited",
    "OILCOUNTUB": "Oil Country Tubular Limited",
    "OISL": "OCLIron and SteelLimited",
    "OLECTRA": "Olectra Greentech Limited",
    "OMAXAUTO": "Omax Autos Limited",
    "OMAXE": "Omaxe Limited",
    "OMKARCHEM": "Omkar Speciality Chemicals Limited",
    "OMMETALS": "OM Metals Infraprojects Limited",
    "ONELIFECAP": "Onelife Capital Advisors Limited",
    "ONEPOINT": "One Point One Solutions Limited",
    "ONGC": "Oil & Natural Gas Corporation Limited",
    "ONMOBILE": "OnMobile Global Limited",
    "ONWARDTEC": "Onward Technologies Limited",
    "OPTIEMUS": "Optiemus Infracom Limited",
    "OPTOCIRCUI": "Opto Circuits (India) Limited",
    "ORBTEXP": "Orbit Exports Limited",
    "ORICONENT": "Oricon Enterprises Limited",
    "ORIENTABRA": "Orient Abrasives Limited",
    "ORIENTALTL": "Oriental Trimex Limited",
    "ORIENTBANK": "Oriental Bank of Commerce",
    "ORIENTBELL": "Orient Bell Limited",
    "ORIENTCEM": "Orient Cement Limited",
    "ORIENTELEC": "Orient Electric Limited",
    "ORIENTHOT": "Oriental Hotels Limited",
    "ORIENTLTD": "Orient Press Limited",
    "ORIENTPPR": "Orient Paper & Industries Limited",
    "ORIENTREF": "Orient Refractories Limited",
    "ORISSAMINE": "The Orissa Minerals Development Company Limited",
    "ORTEL": "Ortel Communications Limited",
    "ORTINLABSS": "Ortin Laboratories Limited",
    "OSWALAGRO": "Oswal Agro Mills Limited",
    "PAEL": "PAE Limited",
    "PAGEIND": "Page Industries Limited",
    "PAISALO": "Paisalo Digital Limited",
    "PALASHSECU": "Palash Securities Limited",
    "PALREDTEC": "Palred Technologies Limited",
    "PANACEABIO": "Panacea Biotec Limited",
    "PANAMAPET": "Panama Petrochem Limited",
    "PAPERPROD": "Huhtamaki PPL Limited",
    "PARABDRUGS": "Parabolic Drugs Limited",
    "PARACABLES": "Paramount Communications Limited",
    "PARAGMILK": "Parag Milk Foods Limited",
    "PARSVNATH": "Parsvnath Developers Limited",
    "PATELENG": "Patel Engineering Limited",
    "PATINTLOG": "Patel Integrated Logistics Limited",
    "PATSPINLTD": "Patspin India Limited",
    "PCJEWELLER": "PCJewellerLimited",
    "PDMJEPAPER": "Pudumjee Paper Products Limited",
    "PDPL": "Parenteral Drugs (India) Limited",
    "PDSMFL": "PDS Multinational Fashions Limited",
    "PEARLPOLY": "Pearl Polymers Limited",
    "PEL": "PiramalEnterprises Limited",
    "PENIND": "Pennar Industries Limited",
    "PENINLAND": "Peninsula Land Limited",
    "PERSISTENT": "Persistent Systems Limited",
    "PETRONENGG": "Petron Engineering Construction Limited",
    "PETRONET": "Petronet LNG Limited",
    "PFC": "Power Finance Corporation Limited",
    "PFIZER": "Pfizer Limited",
    "PFOCUS": "Prime Focus Limited",
    "PFS": "PTC India Financial Services Limited",
    "PGEL": "PG Electroplast Limited",
    "PGHH": "Procter & Gamble Hygiene and Health Care Limited",
    "PGHL": "Procter & Gamble Health Limited",
    "PGIL": "Pearl Global Industries Limited",
    "PHILIPCARB": "PhillipsCarbon BlackLimited",
    "PHOENIXLTD": "The Phoenix Mills Limited",
    "PIDILITIND": "Pidilite IndustriesLimited",
    "PIIND": "PI Industries Limited",
    "PILANIINVS": "Pilani Investment and Industries Corporation Limited",
    "PILITA": "PIL ITALICA LIFESTYLE LIMITED",
    "PIONDIST": "Pioneer Distilleries Limited",
    "PIONEEREMB": "Pioneer Embroideries Limited",
    "PIRPHYTO": "Piramal Phytocare Limited",
    "PITTIENG": "Pitti Engineering Limited",
    "PKTEA": "The Peria Karamalai Tea & Produce Company Limited",
    "PLASTIBLEN": "Plastiblends India Limited",
    "PNB": "Punjab National Bank",
    "PNBGILTS": "PNB Gilts Limited",
    "PNBHOUSING": "PNB Housing Finance Limited",
    "PNC": "Pritish Nandy Communications Limited",
    "PNCINFRA": "PNC InfratechLimited",
    "PODDARHOUS": "Poddar Housing and Development Limited",
    "PODDARMENT": "Poddar Pigments Limited",
    "POKARNA": "Pokarna Limited",
    "POLYCAB": "Polycab India Limited",
    "POLYMED": "Poly Medicure Limited",
    "POLYPLEX": "Polyplex Corporation Limited",
    "PONNIERODE": "Ponni Sugars (Erode) Limited",
    "POWERGRID": "Power Grid Corporation of India Limited",
    "POWERMECH": "Power Mech Projects Limited",
    "PPAP": "PPAP Automotive Limited",
    "PPL": "Prakash Pipes Limited",
    "PRABHAT": "Prabhat Dairy Limited",
    "PRADIP": "Pradip Overseas Limited",
    "PRAENG": "Prajay Engineers Syndicate Limited",
    "PRAJIND": "Praj Industries Limited",
    "PRAKASH": "Prakash Industries Limited",
    "PRAKASHSTL": "Prakash Steelage Limited",
    "PRAXIS": "Praxis Home Retail Limited",
    "PRECAM": "Precision Camshafts Limited",
    "PRECOT": "Precot Meridian Limited",
    "PRECWIRE": "Precision Wires India Limited",
    "PREMEXPLN": "Premier Explosives Limited",
    "PREMIER": "Premier Limited",
    "PREMIERPOL": "Premier Polyfilm Limited",
    "PRESSMN": "Pressman Advertising Limited",
    "PRESTIGE": "Prestige Estates ProjectsLimited",
    "PRICOLLTD": "Pricol Limited",
    "PRIMESECU": "Prime Securities Limited",
    "PROSEED": "Proseed India Limited",
    "PROVOGE": "Provogue (India) Limited",
    "PROZONINTU": "Prozone Intu Properties Limited",
    "PRSMJOHNSN": "Prism Johnson Limited",
    "PSB": "Punjab & Sind Bank",
    "PSL": "PSL Limited",
    "PSPPROJECT": "PSP Projects Limited",
    "PTC": "PTC India Limited",
    "PTL": "PTL Enterprises Limited",
    "PUNJABCHEM": "Punjab Chemicals & Crop Protection Limited",
    "PUNJLLOYD": "Punj Lloyd Limited",
    "PURVA": "Puravankara Limited",
    "PVR": "PVR Limited",
    "QUESS": "Quess Corp Limited",
    "QUICKHEAL": "Quick Heal Technologies Limited",
    "RADAAN": "Radaan Mediaworks India Limited",
    "RADICO": "Radico Khaitan Limited",
    "RADIOCITY": "MusicBroadcast Limited",
    "RAIN": "Rain Industries Limited",
    "RAJESHEXPO": "Rajesh Exports Limited",
    "RAJRAYON": "Raj Rayon Industries Limited",
    "RAJSREESUG": "Rajshree Sugars & Chemicals Limited",
    "RAJTV": "Raj Television Network Limited",
    "RAJVIR": "Rajvir Industries Limited",
    "RALLIS": "Rallis IndiaLimited",
    "RAMANEWS": "Shree Rama Newsprint Limited",
    "RAMASTEEL": "Rama Steel Tubes Limited",
    "RAMCOCEM": "The Ramco Cements Limited",
    "RAMCOIND": "Ramco Industries Limited",
    "RAMCOSYS": "Ramco Systems Limited",
    "RAMKY": "Ramky Infrastructure Limited",
    "RAMSARUP": "Ramsarup Industries Limited",
    "RANASUG": "Rana Sugars Limited",
    "RANEENGINE": "Rane Engine Valve Limited",
    "RANEHOLDIN": "Rane Holdings Limited",
    "RATNAMANI": "Ratnamani Metals & Tubes Limited",
    "RAYMOND": "RaymondLimited",
    "RBL": "Rane Brake Lining Limited",
    "RBLBANK": "RBL Bank Limited",
    "RCF": "Rashtriya Chemicals and Fertilizers Limited",
    "RCOM": "Reliance Communications Limited",
    "RECLTD": "REC Limited",
    "REDINGTON": "Redington (India) Limited",
    "REFEX": "Refex IndustriesLimited",
    "REGENCERAM": "Regency Ceramics Limited",
    "RELAXO": "Relaxo FootwearsLimited",
    "RELCAPITAL": "Reliance Capital Limited",
    "RELIANCE": "Reliance IndustriesLimited",
    "RELIGARE": "Religare Enterprises Limited",
    "RELINFRA": "Reliance Infrastructure Limited",
    "REMSONSIND": "Remsons Industries Limited",
    "RENUKA": "Shree Renuka Sugars Limited",
    "REPCOHOME": "Repco Home Finance Limited",
    "REPRO": "Repro India Limited",
    "RESPONIND": "Responsive Industries Limited",
    "REVATHI": "Revathi Equipment Limited",
    "RGL": "Renaissance Global Limited",
    "RHFL": "Reliance Home Finance Limited",
    "RICOAUTO": "Rico Auto Industries Limited",
    "RIIL": "Reliance Industrial Infrastructure Limited",
    "RITES": "RITES Limited",
    "RKDL": "Ravi Kumar Distilleries Limited",
    "RKFORGE": "Ramkrishna Forgings Limited",
    "RMCL": "Radha Madhav Corporation Limited",
    "RML": "Rane (Madras) Limited",
    "RNAM": "Reliance Nippon Life Asset Management Limited",
    "RNAVAL": "Reliance Naval and Engineering Limited",
    "ROHITFERRO": "Rohit Ferro-Tech Limited",
    "ROHLTD": "Royal Orchid Hotels Limited",
    "ROLLT": "Rollatainers Limited",
    "ROLTA": "Rolta India Limited",
    "ROSSELLIND": "Rossell India Limited",
    "RPGLIFE": "RPG Life Sciences Limited",
    "RPOWER": "Reliance Power Limited",
    "RPPINFRA": "R.P.P. Infra Projects Limited",
    "RSSOFTWARE": "R. S. Software (India) Limited",
    "RSWM": "RSWM Limited",
    "RSYSTEMS": "R Systems International Limited",
    "RTNINFRA": "RattanIndia Infrastructure Limited",
    "RTNPOWER": "RattanIndia Power Limited",
    "RUBYMILLS": "The Ruby Mills Limited",
    "RUCHINFRA": "Ruchi Infrastructure Limited",
    "RUCHIRA": "Ruchira Papers Limited",
    "RUCHISOYA": "Ruchi Soya Industries Limited",
    "RUPA": "Rupa & Company Limited",
    "RUSHIL": "Rushil Decor Limited",
    "RVNL": "Rail Vikas Nigam Limited",
    "SABEVENTS": "Sab Events & Governance Now Media Limited",
    "SABTN": "Sri Adhikari Brothers Television Network Limited",
    "SADBHAV": "Sadbhav Engineering Limited",
    "SADBHIN": "Sadbhav Infrastructure Project Limited",
    "SAFARI": "Safari Industries (India) Limited",
    "SAGARDEEP": "Sagardeep Alloys Limited",
    "SAGCEM": "Sagar Cements Limited",
    "SAIL": "Steel Authority of India Limited",
    "SAKAR": "Sakar Healthcare Limited",
    "SAKHTISUG": "Sakthi Sugars Limited",
    "SAKSOFT": "Saksoft Limited",
    "SAKUMA": "Sakuma Exports Limited",
    "SALASAR": "Salasar Techno Engineering Limited",
    "SALONA": "Salona Cotspin Limited",
    "SALSTEEL": "S.A.L. Steel Limited",
    "SALZERELEC": "Salzer Electronics Limited",
    "SAMBHAAV": "Sambhaav Media Limited",
    "SANCO": "Sanco Industries Limited",
    "SANDESH": "The Sandesh Limited",
    "SANDHAR": "Sandhar Technologies Limited",
    "SANGAMIND": "Sangam (India) Limited",
    "SANGHIIND": "Sanghi Industries Limited",
    "SANGHVIFOR": "Sanghvi Forging and Engineering Limited",
    "SANGHVIMOV": "Sanghvi Movers Limited",
    "SANGINITA": "Sanginita Chemicals Limited",
    "SANOFI": "Sanofi India Limited",
    "SANWARIA": "Sanwaria Consumer Limited",
    "SARDAEN": "Sarda Energy & Minerals Limited",
    "SAREGAMA": "Saregama India Limited",
    "SARLAPOLY": "Sarla Performance Fibers Limited",
    "SASKEN": "Sasken Technologies Limited",
    "SASTASUNDR": "Sastasundar Ventures Limited",
    "SATHAISPAT": "Sathavahana Ispat Limited",
    "SATIA": "Satia Industries Limited",
    "SATIN": "Satin Creditcare Network Limited",
    "SBILIFE": "SBI Life Insurance Company Limited",
    "SBIN": "State Bank of India",
    "SCAPDVR": "Stampede Capital Limited",
    "SCHAEFFLER": "Schaeffler India Limited",
    "SCHAND": "S Chand And Company Limited",
    "SCHNEIDER": "Schneider Electric Infrastructure Limited",
    "SCI": "Shipping Corporation Of India Limited",
    "SDBL": "Som Distilleries & Breweries Limited",
    "SEAMECLTD": "Seamec Limited",
    "SELAN": "Selan Exploration Technology Limited",
    "SELMCL": "SELManufacturing CompanyLimited",
    "SEPOWER": "S.E. Power Limited",
    "SEQUENT": "Sequent Scientific Limited",
    "SESHAPAPER": "Seshasayee Paper and Boards Limited",
    "SETCO": "Setco Automotive Limited",
    "SETUINFRA": "Setubandhan Infrastructure Limited",
    "SEYAIND": "Seya Industries Limited",
    "SEZAL": "Sezal Glass Limited",
    "SFL": "Sheela Foam Limited",
    "SGL": "STL Global Limited",
    "SHAHALLOYS": "Shah Alloys Limited",
    "SHAKTIPUMP": "Shakti Pumps (India) Limited",
    "SHALBY": "Shalby Limited",
    "SHALPAINTS": "Shalimar Paints Limited",
    "SHANKARA": "Shankara BuildingProducts Limited",
    "SHANTIGEAR": "Shanthi Gears Limited",
    "SHARDACROP": "Sharda Cropchem Limited",
    "SHARDAMOTR": "Sharda Motor Industries Limited",
    "SHEMAROO": "Shemaroo Entertainment Limited",
    "SHILPAMED": "Shilpa Medicare Limited",
    "SHIRPUR-G": "Shirpur Gold Refinery Limited",
    "SHIVAMAUTO": "Shivam Autotech Limited",
    "SHIVAMILLS": "Shiva Mills Limited",
    "SHIVATEX": "Shiva Texyarn Limited",
    "SHK": "S H Kelkar and Company Limited",
    "SHOPERSTOP": "Shoppers Stop Limited",
    "SHREDIGCEM": "Shree Digvijay Cement Co.Ltd",
    "SHREECEM": "SHREE CEMENTLIMITED",
    "SHREEPUSHK": "Shree Pushkar Chemicals & Fertilisers Limited",
    "SHREERAMA": "Shree Rama Multi-Tech Limited",
    "SHRENIK": "Shrenik Limited",
    "SHREYANIND": "Shreyans Industries Limited",
    "SHREYAS": "Shreyas Shipping & Logistics Limited",
    "SHRIPISTON": "Shriram Pistons & Rings Limited",
    "SHRIRAMCIT": "Shriram City Union Finance Limited",
    "SHRIRAMEPC": "Shriram EPC Limited",
    "SHYAMCENT": "Shyam Century Ferrous Limited",
    "SHYAMTEL": "Shyam Telecom Limited",
    "SICAGEN": "Sicagen India Limited",
    "SICAL": "Sical Logistics Limited",
    "SIEMENS": "Siemens Limited",
    "SIGIND": "Signet Industries Limited",
    "SIL": "Standard Industries Limited",
    "SILINV": "SIL Investments Limited",
    "SIMBHALS": "Simbhaoli Sugars Limited",
    "SIMPLEXINF": "Simplex Infrastructures Limited",
    "SINTEX": "Sintex Industries Limited",
    "SIRCA": "Sirca Paints India Limited",
    "SIS": "Security and Intelligence Services (India) Limited",
    "SITINET": "Siti Networks Limited",
    "SIYSIL": "SiyaramSilk Mills Limited",
    "SJVN": "SJVN Limited",
    "SKFINDIA": "SKF IndiaLimited",
    "SKIL": "SKIL Infrastructure Limited",
    "SKIPPER": "Skipper Limited",
    "SKMEGGPROD": "SKM Egg Products Export (India) Limited",
    "SMARTLINK": "Smartlink Holdings Limited",
    "SMLISUZU": "SML Isuzu Limited",
    "SMPL": "Splendid Metal Products Limited",
    "SMSLIFE": "SMS Lifesciences India Limited",
    "SMSPHARMA": "SMS Pharmaceuticals Limited",
    "SNOWMAN": "Snowman Logistics Limited",
    "SOBHA": "Sobha Limited",
    "SOLARA": "Solara Active Pharma Sciences Limited",
    "SOLARINDS": "Solar Industries India Limited",
    "SOMANYCERA": "Somany Ceramics Limited",
    "SOMATEX": "Soma Textiles & Industries Limited",
    "SOMICONVEY": "Somi Conveyor Beltings Limited",
    "SONATSOFTW": "Sonata Software Limited",
    "SORILINFRA": "SORIL Infra Resources Limited",
    "SOTL": "Savita Oil Technologies Limited",
    "SOUTHBANK": "The South Indian Bank Limited",
    "SOUTHWEST": "South West Pinnacle Exploration Limited",
    "SPAL": "S. P. Apparels Limited",
    "SPANDANA": "Spandana Sphoorty Financial Limited",
    "SPARC": "Sun PharmaAdvanced Research Company Limited",
    "SPCENET": "Spacenet Enterprises India Limited",
    "SPECIALITY": "Speciality Restaurants Limited",
    "SPENCERS": "Spencer's Retail Limited",
    "SPENTEX": "Spentex Industries Limited",
    "SPIC": "Southern Petrochemicals Industries Corporation Limited",
    "SPICEJET": "SPICEJET LTD",
    "SPLIL": "SPL Industries Limited",
    "SPMLINFRA": "SPML Infra Limited",
    "SPTL": "Sintex Plastics Technology Limited",
    "SPYL": "Shekhawati Poly-Yarn Limited",
    "SREEL": "Sreeleathers Limited",
    "SREINFRA": "SREI Infrastructure Finance Limited",
    "SRF": "SRF Limited",
    "SRHHYPOLTD": "Sree Rayalaseema Hi-Strength Hypo Limited",
    "SRIPIPES": "Srikalahasthi Pipes Limited",
    "SRTRANSFIN": "Shriram Transport Finance Company Limited",
    "SSWL": "Steel Strips Wheels Limited",
    "STAMPEDE": "Stampede Capital Limited",
    "STAR": "Strides Pharma Science Limited",
    "STARCEMENT": "Star Cement Limited",
    "STARPAPER": "Star Paper Mills Limited",
    "STCINDIA": "The State Trading Corporation of India Limited",
    "STEELCITY": "Steel City Securities Limited",
    "STEELXIND": "STEEL EXCHANGE INDIA LIMITED",
    "STEL": "Stel Holdings Limited",
    "STERTOOLS": "Sterling Tools Limited",
    "STINDIA": "STI India Limited",
    "STRTECH": "Sterlite Technologies Limited",
    "SUBCAPCITY": "International Constructions Limited",
    "SUBEX": "Subex Limited",
    "SUBROS": "Subros Limited",
    "SUDARSCHEM": "Sudarshan Chemical Industries Limited",
    "SUJANAUNI": "Sujana Universal Industries Limited",
    "SUMEETINDS": "Sumeet Industries Limited",
    "SUMIT": "Sumit Woods Limited",
    "SUMMITSEC": "Summit Securities Limited",
    "SUNCLAYLTD": "Sundaram Clayton Limited",
    "SUNDARAM": "Sundaram Multi Pap Limited",
    "SUNDARMFIN": "Sundaram Finance Limited",
    "SUNDARMHLD": "Sundaram Finance Holdings Limited",
    "SUNDRMBRAK": "Sundaram Brake Linings Limited",
    "SUNDRMFAST": "Sundram Fasteners Limited",
    "SUNFLAG": "Sunflag Iron AndSteel CompanyLimited",
    "SUNPHARMA": "Sun Pharmaceutical Industries Limited",
    "SUNTECK": "Sunteck Realty Limited",
    "SUNTV": "Sun TV Network Limited",
    "SUPERHOUSE": "Superhouse Limited",
    "SUPERSPIN": "Super Spinning Mills Limited",
    "SUPPETRO": "Supreme Petrochem Limited",
    "SUPRAJIT": "Suprajit Engineering Limited",
    "SUPREMEIND": "Supreme IndustriesLimited",
    "SUPREMEINF": "Supreme Infrastructure India Limited",
    "SURANASOL": "Surana Solar Limited",
    "SURANAT&P": "Surana Telecom and Power Limited",
    "SURYALAXMI": "Suryalakshmi Cotton Mills Limited",
    "SURYAROSNI": "Surya Roshni Limited",
    "SUTLEJTEX": "Sutlej Textiles and Industries Limited",
    "SUVEN": "Suven Life Sciences Limited",
    "SUZLON": "Suzlon Energy Limited",
    "SWANENERGY": "Swan Energy Limited",
    "SWARAJENG": "Swaraj Engines Limited",
    "SWELECTES": "Swelect Energy Systems Limited",
    "SWSOLAR": "Sterling And Wilson Solar Limited",
    "SYMPHONY": "Symphony Limited",
    "SYNCOM": "Syncom Healthcare Limited",
    "SYNDIBANK": "Syndicate Bank",
    "SYNGENE": "Syngene InternationalLimited",
    "TAINWALCHM": "Tainwala Chemical and Plastic (I) Limited",
    "TAJGVK": "Taj GVK Hotels & Resorts Limited",
    "TAKE": "Take Solutions Limited",
    "TALBROAUTO": "Talbros Automotive Components Limited",
    "TALWALKARS": "Talwalkars Better Value Fitness Limited",
    "TALWGYM": "Talwalkars Healthclubs Limited",
    "TANLA": "Tanla Solutions Limited",
    "TANTIACONS": "Tantia Constructions Limited",
    "TARAPUR": "Tarapur Transformers Limited",
    "TARMAT": "Tarmat Limited",
    "TASTYBITE": "Tasty Bite Eatables Limited",
    "TATACHEM": "Tata ChemicalsLimited",
    "TATACOFFEE": "Tata CoffeeLimited",
    "TATACOMM": "Tata CommunicationsLimited",
    "TATAELXSI": "Tata Elxsi Limited",
    "TATAGLOBAL": "Tata Global Beverages Limited",
    "TATAINVEST": "Tata Investment Corporation Limited",
    "TATAMETALI": "Tata Metaliks Limited",
    "TATAMOTORS": "Tata MotorsLimited",
    "TATAMTRDVR": "Tata Motors Limited",
    "TATAPOWER": "Tata Power Company Limited",
    "TATASTEEL": "Tata SteelLimited",
    "TATASTLBSL": "Tata Steel Bsl Limited",
    "TATASTLLP": "Tata Steel Long Products Limited",
    "TBZ": "Tribhovandas Bhimji Zaveri Limited",
    "TCI": "Transport Corporation of India Limited",
    "TCIDEVELOP": "TCI Developers Limited",
    "TCIEXP": "TCI Express Limited",
    "TCIFINANCE": "TCI Finance Limited",
    "TCNSBRANDS": "TCNS ClothingCo. Limited",
    "TCPLPACK": "TCPL Packaging Limited",
    "TCS": "Tata Consultancy Services Limited",
    "TDPOWERSYS": "TD Power Systems Limited",
    "TEAMLEASE": "Teamlease Services Limited",
    "TECHIN": "Techindia Nirman Limited",
    "TECHM": "Tech Mahindra Limited",
    "TECHNOE": "Techno Electric & Engineering Company Limited",
    "TECHNOFAB": "Technofab Engineering Limited",
    "TEJASNET": "Tejas Networks Limited",
    "TERASOFT": "Tera Software Limited",
    "TEXINFRA": "Texmaco Infrastructure & Holdings Limited",
    "TEXMOPIPES": "Texmo Pipes and Products Limited",
    "TEXRAIL": "Texmaco Rail & Engineering Limited",
    "TFCILTD": "Tourism Finance Corporation of India Limited",
    "TFL": "Transwarranty Finance Limited",
    "TGBHOTELS": "TGB Banquets And Hotels Limited",
    "THANGAMAYL": "Thangamayil Jewellery Limited",
    "THEINVEST": "The Investment Trust Of India Limited",
    "THEMISMED": "Themis Medicare Limited",
    "THERMAX": "Thermax Limited",
    "THIRUSUGAR": "Thiru Arooran Sugars Limited",
    "THOMASCOOK": "Thomas Cook (India) Limited",
    "THOMASCOTT": "Thomas Scott (India) Limited",
    "THYROCARE": "Thyrocare Technologies Limited",
    "TI": "Tilaknagar Industries Limited",
    "TIDEWATER": "Tide Water Oil Company (India) Limited",
    "TIIL": "Technocraft Industries (India) Limited",
    "TIINDIA": "Tube Investments of India Limited",
    "TIJARIA": "Tijaria Polypipes Limited",
    "TIL": "TIL Limited",
    "TIMESGTY": "Times Guaranty Limited",
    "TIMETECHNO": "Time Technoplast Limited",
    "TIMKEN": "Timken India Limited",
    "TINPLATE": "The Tinplate Company of India Limited",
    "TIPSINDLTD": "TIPS Industries Limited",
    "TIRUMALCHM": "Thirumalai Chemicals Limited",
    "TITAN": "Titan Company Limited",
    "TMRVL": "The Mandhana Retail Ventures Limited",
    "TNPETRO": "Tamilnadu PetroProducts Limited",
    "TNPL": "Tamil Nadu Newsprint & Papers Limited",
    "TNTELE": "Tamilnadu Telecommunication Limited",
    "TOKYOPLAST": "Tokyo Plast International Limited",
    "TORNTPHARM": "Torrent Pharmaceuticals Limited",
    "TORNTPOWER": "Torrent Power Limited",
    "TPLPLASTEH": "TPL Plastech Limited",
    "TREEHOUSE": "Tree House Education & Accessories Limited",
    "TREJHARA": "TREJHARA SOLUTIONS LIMITED",
    "TRENT": "Trent Limited",
    "TRF": "TRF Limited",
    "TRIDENT": "TridentLimited",
    "TRIGYN": "Trigyn Technologies Limited",
    "TRIL": "Transformers And Rectifiers (India) Limited",
    "TRITURBINE": "Triveni Turbine Limited",
    "TRIVENI": "Triveni Engineering & Industries Limited",
    "TTKHLTCARE": "TTK Healthcare Limited",
    "TTKPRESTIG": "TTK Prestige Limited",
    "TTL": "T T Limited",
    "TTML": "Tata Teleservices (Maharashtra) Limited",
    "TV18BRDCST": "TV18 Broadcast Limited",
    "TVSELECT": "TVS Electronics Limited",
    "TVSMOTOR": "TVS Motor Company Limited",
    "TVSSRICHAK": "TVS Srichakra Limited",
    "TVTODAY": "TV Today Network Limited",
    "TVVISION": "TV Vision Limited",
    "TWL": "Titagarh Wagons Limited",
    "UBL": "United Breweries Limited",
    "UCALFUEL": "Ucal Fuel Systems Limited",
    "UCOBANK": "UCO Bank",
    "UFLEX": "UFLEX Limited",
    "UFO": "UFO Moviez India Limited",
    "UGARSUGAR": "The Ugar Sugar Works Limited",
    "UJAAS": "Ujaas Energy Limited",
    "UJJIVAN": "Ujjivan Financial Services Limited",
    "ULTRACEMCO": "UltraTech CementLimited",
    "UMANGDAIRY": "Umang Dairies Limited",
    "UMESLTD": "Usha Martin Education & Solutions Limited",
    "UNICHEMLAB": "Unichem Laboratories Limited",
    "UNIENTER": "Uniphos Enterprises Limited",
    "UNIONBANK": "Union Bank of India",
    "UNIPLY": "Uniply Industries Limited",
    "UNITECH": "Unitech Limited",
    "UNITEDBNK": "United Bank of India",
    "UNITEDTEA": "The United Nilgiri Tea Estates Company Limited",
    "UNITY": "Unity Infraprojects Limited",
    "UNIVCABLES": "Universal Cables Limited",
    "UPL": "UPLLimited",
    "URJA": "Urja Global Limited",
    "USHAMART": "Usha Martin Limited",
    "UTTAMSTL": "Uttam Galva Steels Limited",
    "UTTAMSUGAR": "Uttam Sugar Mills Limited",
    "UVSL": "Uttam Value Steels Limited",
    "V2RETAIL": "V2 Retail Limited",
    "VADILALIND": "Vadilal Industries Limited",
    "VAIBHAVGBL": "Vaibhav Global Limited",
    "VAKRANGEE": "VakrangeeLimited",
    "VARDHACRLC": "Vardhman Acrylics Limited",
    "VARDMNPOLY": "Vardhman Polytex Limited",
    "VARROC": "Varroc Engineering Limited",
    "VASCONEQ": "Vascon Engineers Limited",
    "VASWANI": "Vaswani Industries Limited",
    "VBL": "Varun BeveragesLimited",
    "VEDL": "Vedanta Limited",
    "VENKEYS": "Venkys (India) Limited",
    "VENUSREM": "Venus Remedies Limited",
    "VESUVIUS": "Vesuvius India Limited",
    "VETO": "Veto Switchgears And Cables Limited",
    "VGUARD": "V-Guard Industries Limited",
    "VHL": "Vardhman Holdings Limited",
    "VICEROY": "Viceroy Hotels Limited",
    "VIDEOIND": "Videocon Industries Limited",
    "VIDHIING": "Vidhi Specialty Food Ingredients Limited",
    "VIJIFIN": "Viji Finance Limited",
    "VIKASECO": "Vikas EcoTech Limited",
    "VIKASMCORP": "Vikas Multicorp Limited",
    "VIKASPROP": "Vikas Proppant & Granite Limited",
    "VIKASWSP": "Vikas WSP Limited",
    "VIMALOIL": "Vimal Oil & Foods Limited",
    "VIMTALABS": "Vimta Labs Limited",
    "VINATIORGA": "Vinati Organics Limited",
    "VINDHYATEL": "Vindhya Telelinks Limited",
    "VINYLINDIA": "Vinyl Chemicals (India) Limited",
    "VIPCLOTHNG": "VIP Clothing Limited",
    "VIPIND": "VIP IndustriesLimited",
    "VIPULLTD": "Vipul Limited",
    "VISAKAIND": "Visaka IndustriesLimited",
    "VISASTEEL": "Visa Steel Limited",
    "VISESHINFO": "Visesh Infotecnics Limited",
    "VISHAL": "Vishal Fabrics Limited",
    "VISHNU": "Vishnu Chemicals Limited",
    "VISHWARAJ": "Vishwaraj Sugar Industries Limited",
    "VIVIDHA": "Visagar Polytex Limited",
    "VIVIMEDLAB": "Vivimed Labs Limited",
    "VLSFINANCE": "VLS Finance Limited",
    "VMART": "V-Mart Retail Limited",
    "VOLTAMP": "Voltamp Transformers Limited",
    "VOLTAS": "Voltas Limited",
    "VRLLOG": "VRL Logistics Limited",
    "VSSL": "Vardhman Special Steels Limited",
    "VSTIND": "VST Industries Limited",
    "VSTTILLERS": "V.S.T TillersTractorsLimited",
    "VTL": "Vardhman Textiles Limited",
    "WABAG": "VA Tech Wabag Limited",
    "WABCOINDIA": "WABCO India Limited",
    "WALCHANNAG": "Walchandnagar Industries Limited",
    "WANBURY": "Wanbury Limited",
    "WATERBASE": "Waterbase Limited",
    "WEBELSOLAR": "Websol Energy System Limited",
    "WEIZFOREX": "Weizmann Forex Limited",
    "WEIZMANIND": "Weizmann Limited",
    "WELCORP": "Welspun Corp Limited",
    "WELENT": "Welspun Enterprises Limited",
    "WELINV": "Welspun Investments and Commercials Limited",
    "WELSPUNIND": "Welspun India Limited",
    "WENDT": "Wendt (India) Limited",
    "WESTLIFE": "Westlife DevelopmentLtd",
    "WHEELS": "Wheels India Limited",
    "WHIRLPOOL": "Whirlpool of India Limited",
    "WILLAMAGOR": "Williamson Magor & Company Limited",
    "WINDMACHIN": "Windsor Machines Limited",
    "WINSOME": "Winsome Yarns Limited",
    "WIPL": "The Western India Plywoods Limited",
    "WIPRO": "WiproLimited",
    "WOCKPHARMA": "Wockhardt Limited",
    "WONDERLA": "Wonderla Holidays Limited",
    "WSI": "W S Industries (I) Limited",
    "WSTCSTPAPR": "West Coast Paper Mills Limited",
    "XCHANGING": "Xchanging Solutions Limited",
    "XELPMOC": "Xelpmoc Design And Tech Limited",
    "XLENERGY": "XL Energy Limited",
    "XPROINDIA": "Xpro India Limited",
    "YESBANK": "Yes Bank Limited",
    "ZEEL": "Zee Entertainment EnterprisesLimited",
    "ZEELEARN": "Zee Learn Limited",
    "ZEEMEDIA": "Zee Media Corporation Limited",
    "ZENITHBIR": "Zenith Birla (India) Limited",
    "ZENITHEXPO": "Zenith Exports Limited",
    "ZENSARTECH": "Zensar Technologies Limited",
    "ZENTEC": "Zen Technologies Limited",
    "ZICOM": "Zicom Electronic Security Systems Limited",
    "ZODIACLOTH": "Zodiac Clothing Company Limited",
    "ZODJRDMKJ": "Zodiac JRD- MKJ Limited",
    "ZOTA": "Zota Health Care LImited",
    "ZUARI": "Zuari Agro Chemicals Limited",
    "ZUARIGLOB": "Zuari Global Limited",
    "ZYDUSWELL": "ZydusWellnessLimited",
}
indices_dict = {
           "BSE": {
              "major_indices": ["SENSEX","BSE 100","BSE 200","BSE 500","BSE MidCap","BSE SmallCap","BSE LargeCap","BSE Sectoral Indices","BSE Bankex","BSE IT","BSE FMCG","BSE Healthcare","BSE Metal","BSE Oil & Gas","BSE Realty","BSE Telecom", "BSE Utilities","BSE Auto","BSE Power","BSE Consumer Durables","BSE Energy","BSE IPO","BSE Infrastructure","BSE Industrials"]},
            "NSE": {
 
              "major_indices": ["NIFTY 50","NIFTY Next 50","NIFTY 100","NIFTY 200","NIFTY 500","NIFTY MidCap 100","NIFTY SmallCap 100","NIFTY MidCap 50","NIFTY SmallCap 50","NIFTY LargeCap 100","NIFTY Sectoral Indices","NIFTY Bank","NIFTY IT","NIFTY FMCG","NIFTY Pharma","NIFTY Auto","NIFTY Metal","NIFTY Realty","NIFTY Energy","NIFTY Infrastructure","NIFTY Media","NIFTY Commodities","NIFTY Financial Services","NIFTY Private Bank","NIFTY PSU Bank"]},
            "US": ["Dow Jones Industrial Average (DJIA)","S&P 500","NASDAQ Composite" ,"Russell 2000","Wilshire 5000","NYSE Composite","CBOE Volatility Index (VIX)"
    ]
}
indices_description= {
    "India": {
        "BSE": {
            "SENSEX": "The benchmark index of the Bombay Stock Exchange, comprising 30 well-established companies.",
            "BSE 100": "Tracks the performance of the top 100 companies listed on the BSE.",
            "BSE 200": "Covers the performance of 200 companies from various sectors.",
            "BSE 500": "A broad market index that tracks the performance of 500 companies across sectors.",
            "BSE MidCap": "Represents the performance of mid-cap companies listed on the BSE.",
            "BSE SmallCap": "Tracks the performance of smaller companies listed on the BSE.",
            "BSE LargeCap": "Represents the performance of large-cap companies listed on the BSE.",
            "BSE Sectoral Indices": "Indexes that track specific sectors like banking, IT, FMCG, and more on the BSE.",
            "BSE Bankex": "Measures the performance of major banking stocks listed on the BSE.",
            "BSE IT": "Tracks the performance of the Information Technology sector.",
            "BSE FMCG": "Represents the performance of the Fast Moving Consumer Goods sector.",
            "BSE Healthcare": "Tracks the performance of companies in the healthcare sector.",
            "BSE Metal": "Measures the performance of the metals sector.",
            "BSE Oil & Gas": "Tracks the performance of companies in the oil & gas sector.",
            "BSE Realty": "Represents the performance of the real estate sector.",
            "BSE Telecom": "Tracks the performance of the telecom sector.",
            "BSE Utilities": "Covers companies providing utility services like electricity and water.",
            "BSE Auto": "Measures the performance of the automobile sector.",
            "BSE Power": "Represents the performance of the power sector.",
            "BSE Consumer Durables": "Tracks companies that manufacture consumer durable goods.",
            "BSE Energy": "Represents companies in the energy sector.",
            "BSE IPO": "Tracks recently listed companies from their initial public offerings (IPOs).",
            "BSE Infrastructure": "Measures the performance of infrastructure-related companies.",
            "BSE Industrials": "Tracks the performance of the industrial sector companies."
        },
        "NSE": {
            "NIFTY 50": "The benchmark index of the National Stock Exchange, consisting of 50 large companies.",
            "NIFTY Next 50": "Tracks the performance of 50 companies next in line after the NIFTY 50.",
            "NIFTY 100": "Measures the performance of the top 100 companies listed on the NSE.",
            "NIFTY 200": "Tracks the performance of 200 companies across sectors.",
            "NIFTY 500": "A broad market index that covers 500 companies listed on the NSE.",
            "NIFTY MidCap 100": "Represents the performance of mid-cap companies on the NSE.",
            "NIFTY SmallCap 100": "Tracks the performance of small-cap companies on the NSE.",
            "NIFTY MidCap 50": "Measures the performance of 50 leading mid-cap companies.",
            "NIFTY SmallCap 50": "Represents 50 prominent small-cap companies.",
            "NIFTY LargeCap 100": "Tracks the performance of large-cap companies listed on the NSE.",
            "NIFTY Sectoral Indices": "Indexes tracking specific sectors like banking, IT, and more on the NSE.",
            "NIFTY Bank": "Measures the performance of major banking stocks listed on the NSE.",
            "NIFTY IT": "Represents the performance of the Information Technology sector.",
            "NIFTY FMCG": "Tracks the performance of the Fast Moving Consumer Goods sector.",
            "NIFTY Pharma": "Measures the performance of pharmaceutical companies.",
            "NIFTY Auto": "Tracks the performance of companies in the automobile sector.",
            "NIFTY Metal": "Represents the performance of the metals sector.",
            "NIFTY Realty": "Measures the performance of real estate sector companies.",
            "NIFTY Energy": "Tracks the performance of the energy sector.",
            "NIFTY Infrastructure": "Represents companies involved in infrastructure development.",
            "NIFTY Media": "Tracks companies in the media and entertainment sector.",
            "NIFTY Commodities": "Measures the performance of commodity-related companies.",
            "NIFTY Financial Services": "Represents the performance of the financial services sector.",
            "NIFTY Private Bank": "Tracks private sector banks listed on the NSE.",
            "NIFTY PSU Bank": "Measures the performance of Public Sector Banks (PSBs) on the NSE."
        }
    },
    "US": {
        "Dow Jones Industrial Average (DJIA)": "Tracks 30 large, publicly-owned companies based in the United States.",
        "S&P 500": "Measures the stock performance of 500 large companies listed on U.S. stock exchanges.",
        "NASDAQ Composite": "Includes over 3,000 stocks listed on the NASDAQ exchange, covering tech-heavy and other sectors.",
        "Russell 2000": "Tracks 2,000 small-cap companies, representing the smallest in the Russell 3000 Index.",
        "Wilshire 5000": "A total market index representing all publicly traded companies with headquarters in the U.S.",
        "NYSE Composite": "Tracks all stocks listed on the New York Stock Exchange (NYSE), including more than 2,000 companies.",
        "CBOE Volatility Index (VIX)": "Measures the market's expectation of volatility based on S&P 500 index options."
    }
}
